-- Auto-generated seed data
USE school_db;

-- PROGRAMS
INSERT INTO program(program_name, department, duration_years, degree_type) VALUES ('Psychologist, educational', 'South', 3, 'PhD');
INSERT INTO program(program_name, department, duration_years, degree_type) VALUES ('Audiological scientist', 'Improve', 4, 'Bachelor');
INSERT INTO program(program_name, department, duration_years, degree_type) VALUES ('Chief of Staff', 'Foot', 3, 'Bachelor');
INSERT INTO program(program_name, department, duration_years, degree_type) VALUES ('Theatre stage manager', 'Attack', 4, 'PhD');
INSERT INTO program(program_name, department, duration_years, degree_type) VALUES ('Teacher, music', 'Development', 3, 'Bachelor');

-- INSTRUCTORS
INSERT INTO instructor(full_name, email, specialization, office_location) VALUES ('Matthew Alvarado', 'jacquelinegreen@example.org', 'Newspaper', 'Room 261');
INSERT INTO instructor(full_name, email, specialization, office_location) VALUES ('Vanessa Johnson', 'wrightcharles@example.org', 'Necessary', 'Room 333');
INSERT INTO instructor(full_name, email, specialization, office_location) VALUES ('Douglas Ellison', 'ethanschwartz@example.com', 'Risk', 'Room 140');
INSERT INTO instructor(full_name, email, specialization, office_location) VALUES ('Stephen Anderson', 'valerie20@example.net', 'Job', 'Room 375');
INSERT INTO instructor(full_name, email, specialization, office_location) VALUES ('William Murray', 'xowen@example.com', 'Who', 'Room 279');
INSERT INTO instructor(full_name, email, specialization, office_location) VALUES ('Brian Garcia', 'ccoleman@example.com', 'Risk', 'Room 206');
INSERT INTO instructor(full_name, email, specialization, office_location) VALUES ('Steven Roberts', 'theodore50@example.com', 'Tv', 'Room 145');
INSERT INTO instructor(full_name, email, specialization, office_location) VALUES ('Christopher Price', 'tyronesmith@example.com', 'Edge', 'Room 333');

-- STUDENTS
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Ethan Travis', '2003-02-09', 'Other', 'laurie59@example.com', '7786184012', '67982 Elizabeth Spurs, Ballardton, GU 67848', 3, 2023);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Elizabeth Wright', '2007-11-18', 'Female', 'sandra47@example.com', '211.944.6197', '6470 Alan Gateway Apt. 850, New Julieville, NM 64011', 3, 2024);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Jessica Lambert', '2005-01-02', 'Female', 'gperez@example.org', '(887)451-0846x558', '18267 Perry Lock, East Michael, FM 75319', 4, 2023);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Susan May', '2004-08-28', 'Male', 'eanderson@example.net', '2857224024', '63859 April Wells Suite 257, Vaughanfort, SC 34218', 5, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Stephanie Griffin', '2007-07-26', 'Other', 'kimberlyvalentine@example.org', '+1-941-360-1527', '95592 Kathy Circles Apt. 305, Johnsonside, VT 25007', 4, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Cheryl Potts', '2005-03-31', 'Female', 'austinmartinez@example.org', '(612)460-7023x381', '48565 Donald Crossing Apt. 377, Kennethborough, CA 88832', 2, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('James Wood', '2006-05-09', 'Female', 'sguzman@example.org', '362-391-9169x094', '1305 Harris Point Suite 491, Andreview, ID 09583', 5, 2023);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Zachary Williams', '1999-12-06', 'Female', 'myersashley@example.net', '491-881-4561', '2493 Duffy Square, New Garrett, CA 38205', 5, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Michael Randall', '2006-06-04', 'Male', 'thompsonlaurie@example.com', '398.722.1492x7769', '742 Jacob Via Suite 556, New Victoria, PW 25758', 3, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Tina Robinson', '2000-06-18', 'Male', 'pwhite@example.org', '870.588.9861', '4367 Salinas Valleys Apt. 116, New Annmouth, CT 86798', 1, 2023);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Kristen Luna', '2002-09-18', 'Female', 'zdelgado@example.org', '001-401-619-9424x44118', '366 Kathy Unions Suite 197, Michaelborough, VT 31215', 4, 2024);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Kenneth Carter', '2002-02-10', 'Other', 'kelly46@example.net', '(417)605-8519x71892', '30598 Michael Greens Suite 686, Port Charles, SC 09300', 5, 2023);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Daniel Newton', '2005-04-27', 'Male', 'smithvalerie@example.org', '(477)484-6801', '27337 Pope Dale Suite 328, Lake Timothyburgh, SC 14513', 4, 2024);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Kathryn Norris', '2000-08-11', 'Female', 'johnsonjacqueline@example.net', '001-353-469-1937', '45120 Patricia Ferry Apt. 851, Kristenstad, KY 31453', 5, 2023);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Jeffrey Jones', '2000-10-01', 'Female', 'abigail25@example.com', '(573)761-7637x47924', '2867 Hayley Causeway Apt. 938, Blevinston, GU 08343', 4, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Jennifer Anderson', '2004-09-15', 'Female', 'michael41@example.net', '001-347-471-1141', '990 Lisa Village, North Nicholasberg, FL 20857', 2, 2024);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Erin Fields', '2006-08-19', 'Female', 'tthomas@example.org', '+1-335-469-1023x80455', '11773 Jillian Route, Davidberg, LA 21720', 5, 2023);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Jennifer Young', '2003-09-28', 'Other', 'emilyhall@example.org', '4792993634', '7056 Chandler Junction Suite 360, Lake Nicolas, ND 87053', 1, 2024);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Neil Thompson', '2002-03-10', 'Male', 'wsmith@example.org', '(263)363-1064x3212', '057 Stewart Spring Apt. 476, South Sherrytown, ME 46550', 2, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Shirley Tyler', '2007-08-19', 'Female', 'adriana89@example.com', '001-454-495-7544x505', 'USCGC Garcia, FPO AE 96096', 5, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Kevin Holland', '2007-02-08', 'Other', 'timstewart@example.net', '928-751-1954x68603', '702 Garcia Springs Suite 167, New Paula, NV 33718', 4, 2023);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Bryan Strickland', '2004-01-01', 'Other', 'mcdonaldchristopher@example.net', '+1-437-411-3029x61964', '7700 Carolyn Stream, Melissaview, ND 84407', 3, 2023);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Emily Martin', '2007-06-23', 'Female', 'nathan83@example.org', '849.669.6569x33508', '02485 Paula Crossroad Suite 289, Bradleyport, NH 57956', 3, 2023);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Joel Vance', '2000-01-23', 'Other', 'meganwells@example.org', '001-427-668-5594x8724', '3160 Lee Brook Apt. 833, Port Ashleyside, MP 90129', 2, 2024);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Vickie Park', '2006-03-22', 'Female', 'dweeks@example.org', '(216)458-8566', 'USNS Molina, FPO AA 40255', 4, 2024);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Stacey Lee', '2004-05-01', 'Female', 'kimberlynielsen@example.net', '+1-310-298-3113x3082', '5357 Holland Parkways Apt. 866, Turnermouth, VT 29660', 5, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Steven Wallace', '2000-05-31', 'Female', 'jesse31@example.com', '296-379-9251', '6221 Tate Mill Apt. 451, Jillianport, LA 79787', 1, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Brandon Horton', '2000-08-26', 'Male', 'gerald11@example.net', '+1-383-502-2679x22600', '7561 Andrea Inlet Suite 282, Barrettshire, NM 55316', 5, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Steven Burns', '2001-11-26', 'Female', 'william03@example.net', '935.912.9529x803', '251 Adam Fields, Petersstad, LA 12274', 5, 2022);
INSERT INTO student(full_name, date_of_birth, gender, email, phone_number, address, program_id, enrollment_year) VALUES ('Mary Macdonald', '2006-11-29', 'Male', 'nancywalton@example.net', '691.750.5721', '451 Atkinson Passage, West Audreyshire, HI 64202', 2, 2024);

-- COURSES
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Synergistic asynchronous array', 2, '2', 5);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Synergistic hybrid focus group', 3, 'Summer', 2);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Digitized explicit migration', 4, 'Summer', 1);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Multi-tiered static protocol', 4, '1', 2);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Reduced 5thgeneration encryption', 4, '2', 2);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Re-engineered radical Graphic Interface', 3, 'Summer', 1);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Upgradable client-driven service-desk', 2, '1', 3);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('User-centric mobile migration', 4, 'Summer', 1);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Cloned coherent success', 2, '2', 3);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Team-oriented zero-defect methodology', 3, 'Summer', 3);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Fully-configurable web-enabled migration', 2, 'Summer', 2);
INSERT INTO course(course_name, credit_hours, semester_offered, program_id) VALUES ('Configurable dynamic model', 3, '2', 5);

-- ENROLLMENTS
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (23, 6, '1', 2023, 3.65, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (10, 9, '1', 2024, 3.65, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (27, 10, '2', 2023, 3.78, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (21, 10, '1', 2023, 2.38, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (14, 1, 'Summer', 2024, 2.61, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (20, 11, 'Summer', 2023, 2.89, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (26, 2, '1', 2023, 3.27, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (18, 4, '2', 2023, 2.49, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (17, 8, 'Summer', 2024, 3.98, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (9, 10, '1', 2023, 3.93, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (29, 6, 'Summer', 2024, 3.68, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (4, 11, '2', 2024, 2.54, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (4, 8, 'Summer', 2024, 3.46, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (25, 9, '1', 2024, 3.75, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (5, 11, 'Summer', 2023, 3.09, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (20, 6, 'Summer', 2023, 3.12, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (6, 1, '1', 2023, 2.11, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (21, 9, 'Summer', 2024, 3.32, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (19, 12, 'Summer', 2023, 2.61, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (12, 11, '2', 2023, 3.81, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (11, 4, '2', 2023, 2.26, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (13, 10, '2', 2024, 2.86, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (25, 3, '1', 2024, 2.49, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (26, 9, 'Summer', 2024, 3.67, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (5, 3, '2', 2023, 3.85, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (20, 11, '1', 2024, 3.74, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (17, 3, '1', 2024, 3.97, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (13, 4, '1', 2023, 2.19, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (3, 7, 'Summer', 2024, 3.09, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (23, 12, '2', 2023, 2.25, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (20, 8, '2', 2023, 3.16, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (8, 12, '1', 2024, 2.74, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (13, 7, 'Summer', 2023, 3.53, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (11, 4, 'Summer', 2024, 3.6, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (16, 2, '1', 2023, 2.57, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (23, 10, '1', 2024, 2.98, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (16, 5, '2', 2023, 3.7, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (6, 10, '1', 2023, 2.65, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (18, 3, '2', 2024, 3.67, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (10, 1, '1', 2023, 3.73, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (29, 6, '1', 2023, 3.5, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (25, 8, 'Summer', 2024, 3.0, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (23, 9, 'Summer', 2024, 2.27, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (30, 3, '1', 2023, 3.4, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (30, 11, 'Summer', 2024, 3.34, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (12, 10, '1', 2023, 2.55, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (2, 11, '1', 2023, 3.86, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (3, 8, 'Summer', 2024, 3.59, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (19, 4, 'Summer', 2023, 3.12, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (15, 9, 'Summer', 2024, 3.33, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (3, 2, '2', 2023, 2.64, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (4, 10, 'Summer', 2023, 3.52, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (2, 1, '1', 2024, 3.33, 'Completed');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (15, 4, 'Summer', 2023, 2.61, 'Withdrawn');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (9, 12, '1', 2023, 2.48, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (21, 8, '1', 2023, 2.05, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (1, 2, '2', 2024, 2.6, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (24, 4, '1', 2024, 2.04, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (7, 10, '1', 2024, 3.15, 'Enrolled');
INSERT INTO enrollment(student_id, course_id, semester, academic_year, grade, status) VALUES (2, 3, '2', 2023, 3.05, 'Completed');

-- TUITION FEES
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (29, 2024, 'Summer', 1200, 1200, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (10, 2023, '2', 1200, 1200, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (27, 2023, '2', 500, 0, 'Unpaid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (10, 2024, '2', 1200, 1200, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (14, 2024, '1', 500, 500, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (10, 2024, '2', 1200, 600.0, 'Partially Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (6, 2024, 'Summer', 800, 0, 'Unpaid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (8, 2024, '2', 500, 0, 'Unpaid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (14, 2024, '1', 1500, 0, 'Unpaid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (25, 2023, '2', 500, 0, 'Unpaid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (12, 2024, '2', 800, 0, 'Unpaid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (11, 2024, '1', 1200, 1200, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (8, 2023, '1', 1500, 1500, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (30, 2023, '1', 500, 250.0, 'Partially Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (28, 2024, '2', 1500, 1500, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (26, 2024, '2', 800, 800, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (12, 2023, '1', 1200, 1200, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (28, 2023, 'Summer', 1200, 0, 'Unpaid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (24, 2023, '2', 1200, 1200, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (30, 2024, 'Summer', 1500, 1500, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (27, 2023, '2', 500, 250.0, 'Partially Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (14, 2024, '1', 800, 400.0, 'Partially Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (10, 2023, 'Summer', 800, 400.0, 'Partially Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (25, 2023, '2', 1200, 600.0, 'Partially Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (4, 2024, 'Summer', 1500, 1500, 'Fully Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (8, 2024, '2', 500, 250.0, 'Partially Paid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (30, 2023, 'Summer', 800, 0, 'Unpaid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (26, 2024, 'Summer', 1500, 0, 'Unpaid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (1, 2023, '2', 1200, 0, 'Unpaid');
INSERT INTO tuition_fee(student_id, academic_year, semester, total_amount, amount_paid, payment_status) VALUES (30, 2024, '1', 800, 800, 'Fully Paid');

-- PAYMENTS
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (9, '2025-07-21', 300, 'Card', 'Ever sister personal.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (25, '2025-11-05', 300, 'Cash', 'Live fact ask else happen.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (21, '2025-11-11', 200, 'Card', 'Ball term first news represent magazine structure.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (25, '2025-02-24', 200, 'Bank Transfer', 'Able site relationship dream again.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (17, '2025-01-28', 500, 'Cash', 'Environmental table out democratic.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (20, '2025-07-21', 500, 'Cash', 'True management option walk.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (1, '2025-08-04', 300, 'Bank Transfer', 'Stop coach focus number room ball.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (15, '2025-05-11', 500, 'Card', 'Mean less card second.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (4, '2024-12-30', 300, 'Cash', 'Necessary civil friend right southern establish quality.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (18, '2025-10-15', 300, 'Cash', 'Girl experience either even clear former factor.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (8, '2025-02-27', 300, 'Card', 'Down road down.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (14, '2025-09-23', 500, 'Bank Transfer', 'Idea gun process.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (15, '2025-04-24', 300, 'Card', 'Role remain similar during.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (13, '2025-06-21', 300, 'Card', 'Choose threat suddenly my morning than cold.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (20, '2024-12-11', 300, 'Cash', 'Center tonight couple.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (7, '2025-08-20', 300, 'Cash', 'Technology well structure fact down.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (6, '2025-02-25', 200, 'Bank Transfer', 'Establish key outside.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (15, '2025-07-26', 200, 'Bank Transfer', 'Beat quality within film production but compare.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (19, '2025-07-20', 500, 'Card', 'Clearly will structure reason wait.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (26, '2025-05-17', 500, 'Card', 'Fast ago pick movement.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (10, '2025-09-03', 300, 'Card', 'Only baby commercial mind play item own.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (3, '2024-12-27', 300, 'Cash', 'Window teacher growth recognize marriage form.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (23, '2025-10-17', 300, 'Cash', 'Experience score drop would.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (17, '2025-01-16', 200, 'Cash', 'Time mention drop leg.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (10, '2025-11-16', 300, 'Card', 'Community lawyer look place us cut.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (20, '2025-09-27', 200, 'Bank Transfer', 'Also benefit senior then sometimes.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (22, '2025-01-12', 500, 'Cash', 'Order finally garden evening popular page seem.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (27, '2025-04-20', 500, 'Bank Transfer', 'Democratic account hard dark suggest section.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (2, '2025-08-03', 300, 'Card', 'Day writer interview feeling.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (26, '2025-05-29', 200, 'Cash', 'May even language policy.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (4, '2025-03-06', 500, 'Cash', 'Artist him standard.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (30, '2025-05-10', 200, 'Bank Transfer', 'Expert social run question.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (14, '2025-10-14', 300, 'Bank Transfer', 'Career might either write oil certain energy.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (5, '2025-09-09', 200, 'Cash', 'Eight data shake four world sit.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (13, '2025-06-13', 300, 'Card', 'Allow painting budget fine bar sometimes institution return.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (24, '2025-11-26', 500, 'Card', 'Near left practice something lay over fast.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (3, '2025-08-13', 200, 'Card', 'Purpose hair especially play knowledge.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (13, '2024-12-13', 500, 'Bank Transfer', 'Present them born growth rock.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (3, '2025-06-23', 500, 'Cash', 'Order mother see year.');
INSERT INTO payment(fee_id, payment_date, amount, payment_method, remarks) VALUES (8, '2025-11-05', 500, 'Card', 'Approach network worker.');

-- ADVISOR ASSIGNMENTS
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (7, 2, '2024-12-29');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (5, 9, '2025-09-01');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (7, 20, '2024-03-28');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (3, 3, '2025-04-06');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (7, 5, '2024-01-13');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (4, 18, '2024-11-12');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (3, 29, '2024-09-22');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (1, 7, '2024-07-01');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (3, 28, '2024-08-03');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (8, 5, '2025-02-01');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (3, 30, '2024-08-13');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (5, 11, '2024-09-01');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (7, 25, '2024-03-31');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (1, 2, '2024-06-03');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (6, 20, '2024-05-12');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (5, 22, '2025-01-13');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (6, 24, '2024-07-10');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (2, 7, '2024-09-20');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (2, 2, '2024-03-20');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (1, 24, '2024-02-09');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (6, 15, '2025-05-15');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (7, 13, '2024-08-20');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (1, 25, '2024-06-04');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (1, 20, '2024-03-10');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (4, 25, '2024-07-17');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (5, 6, '2024-01-15');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (1, 27, '2025-09-11');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (4, 16, '2024-03-01');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (2, 5, '2025-04-30');
INSERT INTO advisor_assignment(instructor_id, student_id, assigned_date) VALUES (3, 25, '2024-07-02');

